DECLARE mDATE_START DATE DEFAULT '{{ (execution_date + macros.timedelta(hours=8) - macros.timedelta(days=3)).strftime("%Y-%m-%d") }}';
DECLARE mDATE_END DATE DEFAULT '{{ (execution_date + macros.timedelta(hours=8) - macros.timedelta(days=0)).strftime("%Y-%m-%d") }}';

-- drop table if exists beautyplus-bc0ed.temp.dws_dz_roas_final_user_behave;
-- create table beautyplus-bc0ed.temp.dws_dz_roas_final_user_behave as


delete from beautyplus-bc0ed.temp.dws_dz_roas_final_user_behave where date between mDATE_START and mDATE_END;
insert into beautyplus-bc0ed.temp.dws_dz_roas_final_user_behave


with goal_users_pre as
(
    select distinct 'ua' types,App_Name app_name
        ,UPPER(Platform) Platform,Attributed_Touch_Date_hk Attributed_Touch_Date,AppsFlyer_ID id
    from `dataintegration-265403.roas_dataset.dwd_dz_af_ua_info`
    where App_Name in ('BeautyPlus') and Attributed_Touch_Date_hk between date_sub(mDATE_START,interval 365 day) and mDATE_END

    union all

    SELECT distinct 'new' types,app_name
          ,upper(Platform) as Platform,event_date_hk as Attributed_Touch_Date,uuid id
    FROM `dataintegration-265403.stat.stat_active_advice_detail_d`
    where app_name in ('BeautyPlus') and is_new = 1 -- 限制新增用户
        and event_date_hk between date_sub(mDATE_START,interval 365 day) and mDATE_END
)
,
uuid_firebase_id as
(
    select key,uuid
    from `dataintegration-265403.stat.dmi_dz_idmapping`
)
,
goal_users as
(
    select distinct types,app_name,Attributed_Touch_Date,uu.uuid
    from goal_users_pre gu
    left join uuid_firebase_id uu
    on gu.id=uu.key
    where gu.types='ua'

    union all

    select distinct types,app_name,Attributed_Touch_Date,id uuid
    from goal_users_pre gu
    where gu.types='new'
)
,
sub_event as
(
    select
        app_id app_name,uuid,standard_order_date,order_status,sum(payment_price_usd) sub_revenue
    from dataintegration-265403.temp.dwd_dz_roi_predict_0_sub_lable_v
    where standard_order_date between mDATE_START and DATE_ADD(mDATE_END,interval 365 day)
        and app_id in('BeautyPlus') and product='subscription' and order_status in (1,2)
    group by 1,2,3,4

    union all

    select
        app_id app_name,uuid,standard_order_date,order_status,sum(payment_price_usd) sub_revenue
    from dataintegration-265403.temp.dwd_dz_roi_predict_0_new_sub_lable_v
    where standard_order_date between mDATE_START and DATE_ADD(mDATE_END,interval 365 day)
        and app_id in('BeautyPlus') and product='subscription' and order_status in (1,2)
    group by 1,2,3,4
)
,
future_sub_pay as
(
    select b.types,a.date,b.Attributed_Touch_Date
        ,b.app_name
        ,b.uuid
--         ,count(case when b.standard_order_date<=a.date then 1 end) sub_now  -- 截止目前用户是否有过订阅（包括试用）
--         ,IFNULL(round(sum(case when b.standard_order_date<=a.date then b.payment_price_usd end),2),0.0) sub_revenue_now  -- 截止目前用户订阅收入
--         ,max(case when b.standard_order_date<=a.date and standard_order_expire_date>=a.date and then 1 else 0 end) is_sub_now  -- 当前用户是否订阅状态（包括试用）
        ,count(case when b.standard_order_date < date_add(b.Attributed_Touch_Date,INTERVAL 365 DAY) then 1 end) sub_365_from_att  -- 投放一年内是否有过订阅行为（不包括试用）
        ,IFNULL(round(sum(case when b.standard_order_date < date_add(b.Attributed_Touch_Date,INTERVAL 365 DAY) then b.sub_revenue end),2),0.0) sub_revenue_365_from_att
    from
    (
        select distinct event_date_hk date
        from `dataintegration-265403.stat.stat_active_advice_detail_d`
        where event_date_hk between mDATE_START and mDATE_END
    ) a
    cross join (select g.types,g.app_name,g.uuid,g.Attributed_Touch_Date,s.standard_order_date,s.sub_revenue from goal_users g left join sub_event s on g.uuid=s.uuid and g.app_name=s.app_name) b
    where (b.standard_order_date between b.Attributed_Touch_Date and DATE_ADD(Attributed_Touch_Date, INTERVAL 364 DAY)) or b.standard_order_date is null
    group by 1,2,3,4,5
)
,
other_info as
(
    select *
    from beautyplus-bc0ed.temp.dws_dz_his_split_final_user_behave
    where date between mDATE_START and mDATE_END
)

select f.types,f.app_name,f.date,f.Attributed_Touch_Date,f.uuid,f.sub_365_from_att,f.sub_revenue_365_from_att
    ,is_current_trial,current_trial_day,is_current_subscription_cancelled,is_current_pay,past_sub_times,trial_times,cancel_subscription_times,refund_subscription_times,promotional_paying_times,id_num,is_new,is_ua,media_source,android_level,permanent_country,platform,brand,model,phone_price,language,operating_system,first_active_date,install_days,last_active_date,last_active_days,active_mins_90d,active_sessions_90d,active_mins_7d,active_sessions_7d,active_category,life_time_active_days,active_days_90d,active_days_7d,active_days_60,active_days_30,active_days_14,active_days_365,holiday_active_days_365,weekend_active_days_365,weekend_include_five_active_days_365,holiday_active_ratio,weekend_active_ratio,weekend_include_five_active_ratio,pv_tab0_edit_entry,pv_tab0_edit_save,pv_tab0_movie_save,pv_tab0_movie_shoot,pv_tab0_selfie_entry,pv_tab0_shoot_save,pv_tab0_shoot_shoot,pv_tab0_video_save,pv_tab0_video_shoot,pv_tab0_videoedit_entry,pv_tab0_videoedit_save,pv_tab1_edit_beauty_click,pv_tab1_edit_beauty_save,pv_tab1_edit_creative_click,pv_tab1_edit_creative_save,pv_tab1_edit_edit_click,pv_tab1_edit_edit_save,pv_tab1_edit_filter_click,pv_tab1_edit_filter_save,pv_tab1_edit_makeup_click,pv_tab1_edit_makeup_save,pv_tab1_edit_senioredit_click,pv_tab1_shoot_ar_save,pv_tab1_shoot_ar_shoot,pv_tab1_shoot_beauty_save,pv_tab1_shoot_filter_save,pv_tab1_shoot_filter_shoot,pv_tab1_shoot_look_save,pv_tab1_shoot_look_shoot,pv_tab1_shoot_makeup_save,pv_tab1_shoot_makeup_shoot,pv_tab2_edit_beauty_AIbeauty_click,pv_tab2_edit_beauty_AIbeauty_save,pv_tab2_edit_beauty_Threedimensionalface_click,pv_tab2_edit_beauty_Threedimensionalface_save,pv_tab2_edit_beauty_detail_click,pv_tab2_edit_beauty_detail_save,pv_tab2_edit_beauty_doublechin_click,pv_tab2_edit_beauty_doublechin_save,pv_tab2_edit_beauty_evenskin_click,pv_tab2_edit_beauty_evenskin_save,pv_tab2_edit_beauty_expression_click,pv_tab2_edit_beauty_expression_save,pv_tab2_edit_beauty_eyecatching_click,pv_tab2_edit_beauty_eyecatching_save,pv_tab2_edit_beauty_eyedilated_click,pv_tab2_edit_beauty_eyedilated_save,pv_tab2_edit_beauty_facecolor_click,pv_tab2_edit_beauty_facecolor_save,pv_tab2_edit_beauty_faceslimming_click,pv_tab2_edit_beauty_faceslimming_save,pv_tab2_edit_beauty_faciallighting_click,pv_tab2_edit_beauty_faciallighting_save,pv_tab2_edit_beauty_facialreshaping_click,pv_tab2_edit_beauty_facialreshaping_save,pv_tab2_edit_beauty_hairdressing_click,pv_tab2_edit_beauty_hairdressing_save,pv_tab2_edit_beauty_lightendarkcircle_click,pv_tab2_edit_beauty_lightendarkcircle_save,pv_tab2_edit_beauty_microdermabrasion_click,pv_tab2_edit_beauty_microdermabrasion_save,pv_tab2_edit_beauty_narrownose_click,pv_tab2_edit_beauty_narrownose_save,pv_tab2_edit_beauty_oneclickbeauty_click,pv_tab2_edit_beauty_oneclickbeauty_save,pv_tab2_edit_beauty_orthodontics_click,pv_tab2_edit_beauty_orthodontics_save,pv_tab2_edit_beauty_removieacne_click,pv_tab2_edit_beauty_removieacne_save,pv_tab2_edit_beauty_removieshine_click,pv_tab2_edit_beauty_removieshine_save,pv_tab2_edit_beauty_removiewrinkles_click,pv_tab2_edit_beauty_removiewrinkles_save,pv_tab2_edit_beauty_shape_click,pv_tab2_edit_beauty_shape_save,pv_tab2_edit_beauty_shrinkhead_click,pv_tab2_edit_beauty_shrinkhead_save,pv_tab2_edit_beauty_teethwhitening_click,pv_tab2_edit_beauty_teethwhitening_save,pv_tab2_edit_creative_background_click,pv_tab2_edit_creative_background_save,pv_tab2_edit_creative_formula_click,pv_tab2_edit_creative_formula_save,pv_tab2_edit_creative_graffiti_click,pv_tab2_edit_creative_graffiti_save,pv_tab2_edit_creative_sticker_click,pv_tab2_edit_creative_sticker_save,pv_tab2_edit_creative_text_click,pv_tab2_edit_creative_text_save,pv_tab2_edit_edit_AIenhance_click,pv_tab2_edit_edit_AIenhance_save,pv_tab2_edit_edit_AIextension_click,pv_tab2_edit_edit_AIextension_save,pv_tab2_edit_edit_adjustment_click,pv_tab2_edit_edit_ar_click,pv_tab2_edit_edit_ar_save,pv_tab2_edit_edit_blur_click,pv_tab2_edit_edit_blur_save,pv_tab2_edit_edit_clone_click,pv_tab2_edit_edit_clone_save,pv_tab2_edit_edit_composition_click,pv_tab2_edit_edit_composition_save,pv_tab2_edit_edit_cutout_click,pv_tab2_edit_edit_cutout_save,pv_tab2_edit_edit_dispersion_click,pv_tab2_edit_edit_dispersion_save,pv_tab2_edit_edit_elimination_click,pv_tab2_edit_edit_elimination_save,pv_tab2_edit_edit_mosaic_click,pv_tab2_edit_edit_mosaic_save,pv_tab2_edit_edit_photorepair_click,pv_tab2_edit_edit_photorepair_save,pv_tab2_edit_edit_stylization_click,pv_tab2_edit_edit_stylization_save,pv_tab2_shoot_beauty_bigeyes_save,pv_tab2_shoot_beauty_eyecatching_save,pv_tab2_shoot_beauty_facecolor_save,pv_tab2_shoot_beauty_faceslimming_save,pv_tab2_shoot_beauty_microdermabrasion_save,pv_tab2_shoot_beauty_oneclickbody_save,pv_tab2_shoot_beauty_removieacnefreckles_save,pv_tab2_shoot_beauty_removiedarkcircles_save,pv_tab2_shoot_beauty_removienasolabial_save,pv_tab2_shoot_beauty_shrinkhead_save,pv_tab2_shoot_beauty_softhair_save,pv_tab2_shoot_beauty_teethwhitening_save,pv_tab2_shoot_beauty_thinnose_save,pv_tab2_shoot_makeup_blush_save,pv_tab2_shoot_makeup_blush_shoot,pv_tab2_shoot_makeup_contactlenses_save,pv_tab2_shoot_makeup_contactlenses_shoot,pv_tab2_shoot_makeup_dyehair_save,pv_tab2_shoot_makeup_dyehair_shoot,pv_tab2_shoot_makeup_eyebrow_save,pv_tab2_shoot_makeup_eyebrow_shoot,pv_tab2_shoot_makeup_eyelash_save,pv_tab2_shoot_makeup_eyelash_shoot,pv_tab2_shoot_makeup_eyeshadow_save,pv_tab2_shoot_makeup_eyeshadow_shoot,pv_tab2_shoot_makeup_freckle_save,pv_tab2_shoot_makeup_freckle_shoot,pv_tab2_shoot_makeup_lipstick_save,pv_tab2_shoot_makeup_lipstick_shoot,pv_tab2_shoot_makeup_lyingsilkworm_save,pv_tab2_shoot_makeup_lyingsilkworm_shoot,pv_tab2_shoot_makeup_trimming_save,pv_tab2_shoot_makeup_trimming_shoot,pv_tab0_edit_entry_30,pv_tab0_edit_save_30,pv_tab0_movie_save_30,pv_tab0_movie_shoot_30,pv_tab0_selfie_entry_30,pv_tab0_shoot_save_30,pv_tab0_shoot_shoot_30,pv_tab0_video_save_30,pv_tab0_video_shoot_30,pv_tab0_videoedit_entry_30,pv_tab0_videoedit_save_30,pv_tab1_edit_beauty_click_30,pv_tab1_edit_beauty_save_30,pv_tab1_edit_creative_click_30,pv_tab1_edit_creative_save_30,pv_tab1_edit_edit_click_30,pv_tab1_edit_edit_save_30,pv_tab1_edit_filter_click_30,pv_tab1_edit_filter_save_30,pv_tab1_edit_makeup_click_30,pv_tab1_edit_makeup_save_30,pv_tab1_edit_senioredit_click_30,pv_tab1_shoot_ar_save_30,pv_tab1_shoot_ar_shoot_30,pv_tab1_shoot_beauty_save_30,pv_tab1_shoot_filter_save_30,pv_tab1_shoot_filter_shoot_30,pv_tab1_shoot_look_save_30,pv_tab1_shoot_look_shoot_30,pv_tab1_shoot_makeup_save_30,pv_tab1_shoot_makeup_shoot_30,pv_tab0_edit_entry_60,pv_tab0_edit_save_60,pv_tab0_movie_save_60,pv_tab0_movie_shoot_60,pv_tab0_selfie_entry_60,pv_tab0_shoot_save_60,pv_tab0_shoot_shoot_60,pv_tab0_video_save_60,pv_tab0_video_shoot_60,pv_tab0_videoedit_entry_60,pv_tab0_videoedit_save_60,pv_tab1_edit_beauty_click_60,pv_tab1_edit_beauty_save_60,pv_tab1_edit_creative_click_60,pv_tab1_edit_creative_save_60,pv_tab1_edit_edit_click_60,pv_tab1_edit_edit_save_60,pv_tab1_edit_filter_click_60,pv_tab1_edit_filter_save_60,pv_tab1_edit_makeup_click_60,pv_tab1_edit_makeup_save_60,pv_tab1_edit_senioredit_click_60,pv_tab1_shoot_ar_save_60,pv_tab1_shoot_ar_shoot_60,pv_tab1_shoot_beauty_save_60,pv_tab1_shoot_filter_save_60,pv_tab1_shoot_filter_shoot_60,pv_tab1_shoot_look_save_60,pv_tab1_shoot_look_shoot_60,pv_tab1_shoot_makeup_save_60,pv_tab1_shoot_makeup_shoot_60,pv_tab0_edit_entry_90,pv_tab0_edit_save_90,pv_tab0_movie_save_90,pv_tab0_movie_shoot_90,pv_tab0_selfie_entry_90,pv_tab0_shoot_save_90,pv_tab0_shoot_shoot_90,pv_tab0_video_save_90,pv_tab0_video_shoot_90,pv_tab0_videoedit_entry_90,pv_tab0_videoedit_save_90,pv_tab1_edit_beauty_click_90,pv_tab1_edit_beauty_save_90,pv_tab1_edit_creative_click_90,pv_tab1_edit_creative_save_90,pv_tab1_edit_edit_click_90,pv_tab1_edit_edit_save_90,pv_tab1_edit_filter_click_90,pv_tab1_edit_filter_save_90,pv_tab1_edit_makeup_click_90,pv_tab1_edit_makeup_save_90,pv_tab1_edit_senioredit_click_90,pv_tab1_shoot_ar_save_90,pv_tab1_shoot_ar_shoot_90,pv_tab1_shoot_beauty_save_90,pv_tab1_shoot_filter_save_90,pv_tab1_shoot_filter_shoot_90,pv_tab1_shoot_look_save_90,pv_tab1_shoot_look_shoot_90,pv_tab1_shoot_makeup_save_90,pv_tab1_shoot_makeup_shoot_90,aigc_enter_pv,aigc_use_pv,aigc_save_pv,pop_exposure,pop_click,content_exposure,content_click,max_module_positon,sub_page_enter,sub_page_click,force_sub_page_enter,force_sub_page_click,subscript_sub_page_enter,subscript_sub_page_click,other_sub_page_enter,other_sub_page_click,max_impression_pv,impression_pv,click_pv,aigc_enter_pv_30,aigc_use_pv_30,aigc_save_pv_30,pop_exposure_30,pop_click_30,content_exposure_30,content_click_30,max_module_positon_30,sub_page_enter_30,sub_page_click_30,force_sub_page_enter_30,force_sub_page_click_30,subscript_sub_page_enter_30,subscript_sub_page_click_30,other_sub_page_enter_30,other_sub_page_click_30,max_impression_pv_30,impression_pv_30,click_pv_30,aigc_enter_pv_60,aigc_use_pv_60,aigc_save_pv_60,pop_exposure_60,pop_click_60,content_exposure_60,content_click_60,max_module_positon_60,sub_page_enter_60,sub_page_click_60,force_sub_page_enter_60,force_sub_page_click_60,subscript_sub_page_enter_60,subscript_sub_page_click_60,other_sub_page_enter_60,other_sub_page_click_60,max_impression_pv_60,impression_pv_60,click_pv_60,aigc_enter_pv_90,aigc_use_pv_90,aigc_save_pv_90,pop_exposure_90,pop_click_90,content_exposure_90,content_click_90,max_module_positon_90,sub_page_enter_90,sub_page_click_90,force_sub_page_enter_90,force_sub_page_click_90,subscript_sub_page_enter_90,subscript_sub_page_click_90,other_sub_page_enter_90,other_sub_page_click_90,max_impression_pv_90,impression_pv_90,click_pv_90,puzzle_click_pv,puzzle_save_pv,puzzle_click_pv_30,puzzle_save_pv_30,puzzle_click_pv_60,puzzle_save_pv_60,puzzle_click_pv_90,puzzle_save_pv_90,pay_function_click_pv,free_function_click_pv,free_function_save_pv,pay_function_click_pv_30,free_function_click_pv_30,free_function_save_pv_30,pay_function_click_pv_60,free_function_click_pv_60,free_function_save_pv_60,pay_function_click_pv_90,free_function_click_pv_90,free_function_save_pv_90,pay_duffle_click_pv,free_duffle_click_pv,free_duffle_save_pv,pay_duffle_click_pv_30,free_duffle_click_pv_30,free_duffle_save_pv_30,pay_duffle_click_pv_60,free_duffle_click_pv_60,free_duffle_save_pv_60,pay_duffle_click_pv_90,free_duffle_click_pv_90,free_duffle_save_pv_90,function_num,function_num_pre,function_num_30,function_num_60,function_num_90,grow_function_num,homepage_exposure_pv,homepage_click_pv,homepage_feature_show_pv,homepage_feature_click_pv,homepage_banner_show_pv,homepage_banner_click_pv,homepage_reconmend_show_pv,homepage_reconmend_click_pv,homepage_topic_show_pv,homepage_topic_click_pv,homepage_miniapp_show_pv,homepage_miniapp_click_pv,homepage_exposure_pv_30,homepage_click_pv_30,homepage_feature_show_pv_30,homepage_feature_click_pv_30,homepage_banner_show_pv_30,homepage_banner_click_pv_30,homepage_reconmend_show_pv_30,homepage_reconmend_click_pv_30,homepage_topic_show_pv_30,homepage_topic_click_pv_30,homepage_miniapp_show_pv_30,homepage_miniapp_click_pv_30,homepage_exposure_pv_60,homepage_click_pv_60,homepage_feature_show_pv_60,homepage_feature_click_pv_60,homepage_banner_show_pv_60,homepage_banner_click_pv_60,homepage_reconmend_show_pv_60,homepage_reconmend_click_pv_60,homepage_topic_show_pv_60,homepage_topic_click_pv_60,homepage_miniapp_show_pv_60,homepage_miniapp_click_pv_60,homepage_exposure_pv_90,homepage_click_pv_90,homepage_feature_show_pv_90,homepage_feature_click_pv_90,homepage_banner_show_pv_90,homepage_banner_click_pv_90,homepage_reconmend_show_pv_90,homepage_reconmend_click_pv_90,homepage_topic_show_pv_90,homepage_topic_click_pv_90,homepage_miniapp_show_pv_90,homepage_miniapp_click_pv_90,bucket
from future_sub_pay f
left join other_info o
on o.uuid=f.uuid and o.app_name=f.app_name and o.date=f.date
where f.date between f.Attributed_Touch_Date and date_add(f.Attributed_Touch_Date,interval 364 day)


